apiVersion: v1
kind: Pod
metadata:
  name: jar-pod
  labels:
    app: myapp

spec:
  containers:
    - name: jar-pod-container
      image: imajeetyadav/jar-cicd
      ports:
        - containerPort: 8080
          name: http-web-svc
      resources:
        limits:
          memory: 512Mi
          cpu: "0.5"
        requests:
          memory: 256Mi
          cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instace
  name: jar-service

spec:
  selector:
    app: myapp

  ports:
    - port: 8088
      targetPort: http-web-svc
      protocol: TCP
      nodePort: 30163

  # Types available in local are ClusterIP and NodePort
  type: LoadBalancer
